services:
  email-service-mga:
    container_name: email-service-mga
    image: fabriziodevar/email-service-mga:latest
    ports:
      - 8080:4100
    environment:
      MAIL_ENABLED: ${MAIL_ENABLED}
      TZ: ${TZ}
      FRONT_HOST: ${FRONT_HOST}
      HOST_METHODS: ${HOST_METHODS}
      HOST_ALLOWED_HEADERS: ${HOST_ALLOWED_HEADERS}
      HOST_CREDENTIALS: ${HOST_CREDENTIALS}
      TRANSPORT_FALLBACK: ${TRANSPORT_FALLBACK}
      EMAIL_FROM: ${EMAIL_FROM}
      # Mailing
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      # RabbitMQ
      RABBITMQ_PROTOCOL: ${RABBITMQ_PROTOCOL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_COLAS: ${RABBITMQ_COLAS}
    restart: always
    networks:
      - services-nwk

networks:
  services-nwk:
    external: true
