name: Create Domain in Nginx Proxy Manager

on:
  workflow_run:
    workflows: ['Deploy to Portainer']
    types:
      - completed

jobs:
  create_domain:
    name: Create domain
    runs-on: ubuntu-latest

    steps:
      - name: Get Nginx Proxy Manager token
        id: get-token
        run: |
          response=$(curl -s -X POST "${{ secrets.NPM_HOST }}/api/tokens" \
           -H "Content-Type: application/json" \
           -d '{"identity":"${{ secrets.NPM_USER }}", "secret":"${{ secrets.NPM_PASS }}"}')
           token=$(echo $response | jq -r '.token')

           if [[ -z "$token" || "$token" == "null" ]]; then
             echo "Error: Token is empty or null"
             exit 1
           fi

           echo "TOKEN=$token" >> $GITHUB_ENV

      - name: Create domain in Nginx Proxy Manager
        run: |
          curl -X POST "${{ secrets.NPM_HOST }}/api/nginx/proxy-hosts" \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "domain_names": ["${{ secrets.NPM_DOMAIN_APP }}"],
              "forward_scheme": "${{ secrets.HTTP_SCHEME }}",
              "forward_host": "${{ secrets.DOCKER_HOST_APP }}",
              "forward_port": ${{ secrets.DOCKER_PORT }},
              "access_list_id": "0",
              "certificate_id": 0,
              "meta": {
                "letsencrypt_agree": false,
                "dns_challenge": false
              },
              "advanced_config": "",
              "locations": [],
              "block_exploits": false,
              "caching_enabled": false,
              "allow_websocket_upgrade": false,
              "http2_support": false,
              "hsts_enabled": false,
              "hsts_subdomains": false,
              "ssl_forced": false
            }'
